services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REQUIREMENTS_FILE=requirements/prod.txt

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=config.settings